'use client'
import {useRef,useState} from 'react'
import {useStaffData} from './staff-session'
import {apiFetch,jsonHeaders} from '@/lib/staff-client'
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
export function StudentHomework({studentId}:{studentId:string}){
 const [items,setItems]=useState<any[]>([]),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[error,setError]=useState(''),[link,setLink]=useState(''),[form,setForm]=useState({title:'',details:'',assigned_on:today(),due_on:today()});const pending=useRef<string>('')
 const url=`/api/admin/students/${studentId}/homework`
 useStaffData(load)
 async function load(){try{const r=await apiFetch(url),d=await r.json();if(!r.ok)throw Error(d.error);setItems(d.items??[])}catch(e){setError(String(e))}}
 async function send(body:any){if(busy)return;setBusy(true);setError('');try{const r=await apiFetch(url,{method:'POST',headers:jsonHeaders,body:JSON.stringify(body)}),d=await r.json();if(!r.ok){if(r.status<500){setUncertain(false);pending.current=''}throw Error(d.error)}if(d.url)setLink(d.url);if(body.action==='revoke')setLink('');if(body.action==='assign'){setUncertain(false);pending.current='';setForm({...form,title:'',details:''})}await load()}catch(e){setError(body.action==='assign'?'저장 결과를 확인하지 못했습니다. 같은 내용으로 다시 눌러 주세요.':String(e))}finally{setBusy(false)}}
 return <section id="student-homework" className="surface"><div className="section-heading"><h2>과제와 학생 입장</h2><button className="button" disabled={busy} onClick={load}>과제 새로고침</button></div><p>학생 전용 링크는 30일간 유효합니다. 새 링크를 만들면 이전 링크는 종료됩니다. 해당 학생과 보호자에게만 전달하세요.</p><div className="access-controls"><button className="button" disabled={busy} onClick={()=>send({action:'link'})}>학생 링크 새로 만들기</button><button className="button" disabled={busy} onClick={()=>send({action:'revoke'})}>학생 링크 종료</button></div>{link&&<label className="field"><span>학생 입장 링크 · 길게 눌러 복사</span><input readOnly value={link}/><a href={link} target="_blank" rel="noreferrer">학생 화면 열기</a></label>}
 <form aria-label="과제 등록" onSubmit={e=>{e.preventDefault();pending.current ||= crypto.randomUUID();setUncertain(true);void send({action:'assign',id:pending.current,...form})}}><fieldset disabled={busy||uncertain} className="progress-fields"><label className="field"><span>과제명</span><input required maxLength={200} value={form.title} onChange={e=>{pending.current='';setForm({...form,title:e.target.value})}}/></label><label className="field"><span>시작일</span><input required type="date" value={form.assigned_on} onChange={e=>{pending.current='';setForm({...form,assigned_on:e.target.value})}}/></label><label className="field"><span>마감일</span><input required type="date" min={form.assigned_on} value={form.due_on} onChange={e=>{pending.current='';setForm({...form,due_on:e.target.value})}}/></label><label className="field"><span>교재·쪽수·안내</span><textarea maxLength={2000} value={form.details} onChange={e=>{pending.current='';setForm({...form,details:e.target.value})}}/></label></fieldset><button className="button button-primary" disabled={busy}>{uncertain?'저장 결과 확인':'과제 등록'}</button></form>
 <p role="status">{error}</p><div className="table-scroll"><table className="data-table"><thead><tr><th>과제 / 마감일</th><th>제출 상태</th><th>사진</th></tr></thead><tbody>{items.map(h=><tr key={h.id}><td>{h.title}<small>{h.details}</small><small>{h.due_on}</small></td><td><select aria-label={`${h.title} 제출 상태`} value={h.status} disabled={busy} onChange={e=>send({action:'status',homework_id:h.id,status:e.target.value})}><option value="assigned">미제출</option><option value="submitted">제출</option><option value="checked">강사 확인</option></select></td><td>{h.photos.map((p:any,i:number)=><a key={p.id} href={p.url} target="_blank" rel="noreferrer">사진 {i+1} </a>)}</td></tr>)}</tbody></table></div><p className="meta">최근 마감일 순 100개 · 사진 링크는 5분 후 만료되며 새로고침하면 다시 열립니다. 직접 받은 숙제도 제출 상태를 바꿔 기록할 수 있습니다.</p></section>
}
