-- No messages are sent. All fixtures and simulated delivery states are rolled back.
begin;
do $$
declare
  institution uuid; teacher uuid; program uuid; staff uuid; foreign_staff uuid;
  guardian uuid; pupil uuid; report_token_value uuid; report_id_value uuid; attempt_id uuid; result jsonb; rejected boolean;
begin
  insert into moasem.institutions(name) values('__alimtalk_test__') returning id into institution;
  insert into moasem.instructors(name) values('__alimtalk_teacher__') returning id into teacher;
  insert into moasem.programs(institution_id,instructor_id,name,starts_on,ends_on,week_count) values(institution,teacher,'__alimtalk_program__','2026-01-01','2026-12-31',12) returning id into program;
  staff := moasem.save_staff_instructor(null,teacher,null,'__alimtalk_teacher__','test-'||gen_random_uuid()||'@example.invalid','',array[program],true);
  foreign_staff := moasem.save_staff_instructor(null,null,null,'__foreign__','test-'||gen_random_uuid()||'@example.invalid','','{}',true);
  insert into moasem.guardians(name,phone) values('__test_recipient__','+82 10-0000-0000') returning id into guardian;
  insert into moasem.students(program_id,guardian_id,name,grade) values(program,guardian,'__test_pupil__',3) returning id into pupil;
  report_token_value := (moasem.create_staff_learning_report(staff,pupil,'{"lesson_date":"2026-09-05","solved_count":10,"wrong_count":1,"language":"ko"}','{}')->>'token')::uuid;
  select id into report_id_value from moasem.guardian_reports r where r.token=report_token_value;
  set local role service_role;
  result := moasem.claim_report_notification(staff,report_token_value,false);
  if not (result->>'claimed')::boolean or result->'attempt'->>'recipient_phone'<>'01000000000' then raise exception 'Claim or phone normalization failed'; end if;
  attempt_id := (result->'attempt'->>'id')::uuid;
  if (moasem.claim_report_notification(staff,report_token_value,false)->>'claimed')::boolean then raise exception 'Duplicate click claimed another send'; end if;
  rejected := false;
  begin
    insert into moasem.report_notification_attempts(report_id,recipient_phone,status) values(report_id_value,'01000000000','accepted');
  exception when unique_violation then rejected := true;
  end;
  if not rejected then raise exception 'Database uniqueness guard missing'; end if;
  update moasem.report_notification_attempts set status='unknown' where id=attempt_id;
  if (moasem.claim_report_notification(staff,report_token_value,true)->>'claimed')::boolean then raise exception 'Uncertain send was retried'; end if;
  update moasem.report_notification_attempts set status='failed' where id=attempt_id;
  rejected := false;
  begin perform moasem.claim_report_notification(staff,report_token_value,true);
  exception when others then if sqlerrm<>'RETRY_LIMIT' then raise; end if; rejected := true; end;
  if not rejected then raise exception 'Retry cooldown missing'; end if;
  update moasem.report_notification_attempts set created_at=now()-interval '2 minutes' where id=attempt_id;
  if (moasem.claim_report_notification(staff,report_token_value,false)->>'claimed')::boolean then raise exception 'Failure retried without explicit request'; end if;
  result := moasem.claim_report_notification(staff,report_token_value,true);
  if not (result->>'claimed')::boolean then raise exception 'Confirmed failure could not be retried'; end if;
  update moasem.report_notification_attempts set status='failed',created_at=now()-interval '1 minute' where id=(result->'attempt'->>'id')::uuid;
  result := moasem.claim_report_notification(staff,report_token_value,true);
  update moasem.report_notification_attempts set status='failed',created_at=now()-interval '61 seconds' where id=(result->'attempt'->>'id')::uuid;
  rejected := false;
  begin perform moasem.claim_report_notification(staff,report_token_value,true);
  exception when others then if sqlerrm<>'RETRY_LIMIT' then raise; end if; rejected := true; end;
  if not rejected then raise exception 'Retry attempt limit missing'; end if;

  rejected := false;
  begin perform moasem.claim_report_notification(foreign_staff,report_token_value,false);
  exception when others then if sqlerrm<>'PROGRAM_ACCESS_DENIED' then raise; end if; rejected := true; end;
  if not rejected then raise exception 'Foreign instructor allowed'; end if;
  update moasem.guardian_reports set expires_at=now()-interval '1 second' where id=report_id_value;
  rejected := false;
  begin perform moasem.claim_report_notification(staff,report_token_value,false);
  exception when others then if sqlerrm<>'REPORT_EXPIRED' then raise; end if; rejected := true; end;
  if not rejected then raise exception 'Expired report sent'; end if;
  update moasem.guardian_reports set expires_at=now()+interval '14 days' where id=report_id_value;
  update moasem.students set guardian_id=null where id=pupil;
  rejected := false;
  begin perform moasem.claim_report_notification(staff,report_token_value,false);
  exception when others then if sqlerrm<>'GUARDIAN_CHANGED' then raise; end if; rejected := true; end;
  if not rejected then raise exception 'Changed guardian sent old report'; end if;
  update moasem.students set guardian_id=guardian where id=pupil;
  update moasem.guardians set phone='not a phone' where id=guardian;
  rejected := false;
  begin perform moasem.claim_report_notification(staff,report_token_value,false);
  exception when others then if sqlerrm<>'INVALID_PHONE' then raise; end if; rejected := true; end;
  if not rejected then raise exception 'Invalid recipient accepted'; end if;
  update moasem.staff_accounts set active=false where id=staff;
  rejected := false;
  begin perform moasem.claim_report_notification(staff,report_token_value,false);
  exception when others then if sqlerrm<>'STAFF_ACCESS_DENIED' then raise; end if; rejected := true; end;
  if not rejected then raise exception 'Inactive account allowed'; end if;
  if (select count(*) from moasem.report_notification_attempts where report_id=report_id_value)<>3 then raise exception 'Rejected requests created attempts'; end if;
  reset role;
  if has_table_privilege('anon','moasem.report_notification_attempts','SELECT') or has_table_privilege('authenticated','moasem.report_notification_attempts','SELECT') then raise exception 'Notification contacts exposed'; end if;
  if has_function_privilege('anon','moasem.claim_report_notification(uuid,uuid,boolean)','EXECUTE') or has_function_privilege('authenticated','moasem.claim_report_notification(uuid,uuid,boolean)','EXECUTE') then raise exception 'Claim callable by browser'; end if;
  if not (select relrowsecurity from pg_class where oid='moasem.report_notification_attempts'::regclass) then raise exception 'Notification RLS missing'; end if;
end;
$$;
rollback;
