-- Test fixtures only; no real consent, Auth account, notification or retained data.
begin;
do $$
declare institution_id_value uuid; teacher_id uuid; program_id_value uuid; staff_id_value uuid; admin_id_value uuid; foreign_staff uuid;
  guardian_id_value uuid; pupil_id uuid; document_id_value uuid; request_id_value uuid;
  result jsonb; receipt_time timestamptz; rejected boolean; table_name_value text;
  texts jsonb := '{"ko":{"title":"시험 문구","body":"실제 동의 문구가 아닌 검증 자료"},"vi":{"title":"Test only","body":"Not a real consent document"}}';
  submission jsonb;
begin
  insert into moasem.institutions(name) values('__consent_test__') returning id into institution_id_value;
  insert into moasem.instructors(name) values('__consent_teacher__') returning id into teacher_id;
  insert into moasem.programs(institution_id,instructor_id,name,starts_on,ends_on,week_count)
    values(institution_id_value,teacher_id,'__consent_program__','2026-01-01','2026-12-31',12) returning id into program_id_value;
  staff_id_value := moasem.save_staff_instructor(null,teacher_id,null,'__test_teacher__','test-'||gen_random_uuid()||'@example.invalid','',array[program_id_value],true);
  foreign_staff := moasem.save_staff_instructor(null,null,null,'__test_foreign__','test-'||gen_random_uuid()||'@example.invalid','','{}',true);
  insert into moasem.staff_accounts(name,email,role) values('__consent_test_admin__','test-'||gen_random_uuid()||'@example.invalid','admin') returning id into admin_id_value;
  insert into moasem.guardians(name,phone,language) values('__test_guardian__','01000000000','vi') returning id into guardian_id_value;
  insert into moasem.students(program_id,guardian_id,name,grade) values(program_id_value,guardian_id_value,'__test_pupil__',3) returning id into pupil_id;
  set local role service_role;
  rejected := false;
  begin perform moasem.publish_consent_document(staff_id_value,'test',texts);
  exception when others then if sqlerrm<>'STAFF_ACCESS_DENIED' then raise; end if; rejected := true; end;
  if not rejected then raise exception 'Instructor changed legal text'; end if;
  rejected := false;
  begin perform moasem.publish_consent_document(admin_id_value,'test',texts-'ko');
  exception when others then if sqlerrm<>'KOREAN_REQUIRED' then raise; end if; rejected := true; end;
  if not rejected then raise exception 'Missing Korean accepted'; end if;
  rejected := false;
  begin perform moasem.publish_consent_document(admin_id_value,'test','{"ko":{"title":"x","body":""}}');
  exception when others then if sqlerrm<>'INVALID_DOCUMENT' then raise; end if; rejected := true; end;
  if not rejected then raise exception 'Empty legal copy accepted'; end if;
  document_id_value := (moasem.publish_consent_document(admin_id_value,'test',texts)->>'id')::uuid;
  rejected := false;
  begin perform moasem.create_guardian_consent_request(foreign_staff,pupil_id,document_id_value,repeat('a',64));
  exception when others then if sqlerrm<>'PROGRAM_ACCESS_DENIED' then raise; end if; rejected := true; end;
  if not rejected then raise exception 'Foreign teacher issued link'; end if;
  result := moasem.create_guardian_consent_request(staff_id_value,pupil_id,document_id_value,repeat('a',64));
  request_id_value := (result->>'id')::uuid;
  if result->>'language'<>'vi' or (result->>'expires_at')::timestamptz<>now()+interval '7 days' then raise exception 'Language or expiry wrong'; end if;
  result := moasem.access_guardian_consent(repeat('a',64));
  if result->>'status'<>'pending' or result->'document'->'primary'->>'body'<>texts->'vi'->>'body'
    or result ? 'guardian_phone' or result ? 'student_id' or result ? 'token_hash' then raise exception 'Public document is incorrect or overexposed'; end if;
  if exists(select 1 from moasem.guardian_consent_records where request_id=request_id_value) then raise exception 'Reading counted as consent'; end if;
  submission := jsonb_build_object('accepted',true,'is_legal_representative',true,'signer_name','Test guardian','language','vi','document_id',document_id_value);
  rejected := false;
  begin perform moasem.access_guardian_consent(repeat('a',64),submission||'{"accepted":false}');
  exception when others then if sqlerrm<>'INVALID_CONSENT' then raise; end if; rejected := true; end;
  if not rejected then raise exception 'False consent recorded'; end if;
  rejected := false;
  begin perform moasem.access_guardian_consent(repeat('a',64),submission||'{"language":"ko"}');
  exception when others then if sqlerrm<>'INVALID_CONSENT' then raise; end if; rejected := true; end;
  if not rejected then raise exception 'Unread language recorded'; end if;
  rejected := false;
  begin perform moasem.access_guardian_consent(repeat('a',64),submission||jsonb_build_object('document_id',gen_random_uuid()));
  exception when others then if sqlerrm<>'INVALID_CONSENT' then raise; end if; rejected := true; end;
  if not rejected then raise exception 'Unread document recorded'; end if;
  result := moasem.access_guardian_consent(repeat('a',64),submission||'{"consented_at":"1999-01-01","verification_method":"phone_verified"}');
  receipt_time := (result->>'consented_at')::timestamptz;
  if result->>'status'<>'accepted' or receipt_time<>now() then raise exception 'Consent timestamp is not server authoritative'; end if;
  perform moasem.access_guardian_consent(repeat('a',64),submission);
  if (select count(*) from moasem.guardian_consent_records where request_id=request_id_value)<>1 then raise exception 'Duplicate consent inserted'; end if;
  if (select verification_method from moasem.guardian_consent_records where request_id=request_id_value)<>'link_self_declaration' then raise exception 'Identity proof was falsely claimed'; end if;
  rejected := false;
  begin perform moasem.access_guardian_consent(repeat('a',64),submission||'{"signer_name":"Someone else"}');
  exception when others then if sqlerrm<>'CONSENT_ALREADY_RECORDED' then raise; end if; rejected := true; end;
  if not rejected then raise exception 'Consent signer overwritten'; end if;
  -- New wording never mutates the copy actually agreed to.
  perform moasem.publish_consent_document(admin_id_value,'new version',jsonb_set(texts,'{vi,body}','"Changed later"'));
  if moasem.access_guardian_consent(repeat('a',64))->'document'->'primary'->>'body'<>texts->'vi'->>'body' then raise exception 'Old consent text drifted'; end if;
  rejected := false;
  begin update moasem.guardian_consent_records set signer_name='Changed' where request_id=request_id_value;
  exception when insufficient_privilege then rejected := true; end;
  if not rejected then raise exception 'App can overwrite consent evidence'; end if;
  rejected := false;
  begin update moasem.consent_documents set translations='{}' where id=document_id_value;
  exception when insufficient_privilege then rejected := true; end;
  if not rejected then raise exception 'App can rewrite published copy'; end if;
  -- Reissuing disables old capabilities but preserves their immutable evidence.
  result := moasem.create_guardian_consent_request(staff_id_value,pupil_id,document_id_value,repeat('b',64));
  rejected := false;
  begin perform moasem.access_guardian_consent(repeat('a',64),submission);
  exception when others then if sqlerrm<>'CONSENT_UNAVAILABLE' then raise; end if; rejected := true; end;
  if not rejected then raise exception 'Superseded capability still works'; end if;
  if not exists(select 1 from moasem.guardian_consent_records where request_id=request_id_value and consented_at=receipt_time) then raise exception 'Reissue erased evidence'; end if;
  request_id_value := (result->>'id')::uuid;
  rejected := false;
  begin perform moasem.revoke_guardian_consent_request(foreign_staff,pupil_id,request_id_value);
  exception when others then if sqlerrm<>'PROGRAM_ACCESS_DENIED' then raise; end if; rejected := true; end;
  if not rejected then raise exception 'Foreign teacher revoked link'; end if;
  update moasem.guardians set phone='01011111111' where id=guardian_id_value;
  rejected := false;
  begin perform moasem.access_guardian_consent(repeat('b',64));
  exception when others then if sqlerrm<>'CONSENT_UNAVAILABLE' then raise; end if; rejected := true; end;
  if not rejected then raise exception 'Old recipient can still use link'; end if;
  update moasem.guardians set phone='01000000000' where id=guardian_id_value;
  update moasem.students set guardian_id=null where id=pupil_id;
  rejected := false;
  begin perform moasem.access_guardian_consent(repeat('b',64),submission);
  exception when others then if sqlerrm<>'CONSENT_UNAVAILABLE' then raise; end if; rejected := true; end;
  if not rejected then raise exception 'Removed guardian can still sign'; end if;
  update moasem.students set guardian_id=guardian_id_value where id=pupil_id;
  -- Change only rolled-back test expiry using the migration owner role.
  reset role;
  update moasem.guardian_consent_requests set created_at=now()-interval '8 days',expires_at=now()-interval '1 second' where id=request_id_value;
  set local role service_role;
  rejected := false;
  begin perform moasem.access_guardian_consent(repeat('b',64),submission);
  exception when others then if sqlerrm<>'CONSENT_UNAVAILABLE' then raise; end if; rejected := true; end;
  if not rejected then raise exception 'Expired consent accepted'; end if;
  result := moasem.create_guardian_consent_request(staff_id_value,pupil_id,document_id_value,repeat('c',64));
  perform moasem.revoke_guardian_consent_request(staff_id_value,pupil_id,(result->>'id')::uuid);
  rejected := false;
  begin perform moasem.access_guardian_consent(repeat('c',64),submission);
  exception when others then if sqlerrm<>'CONSENT_UNAVAILABLE' then raise; end if; rejected := true; end;
  if not rejected then raise exception 'Revoked consent accepted'; end if;
  update moasem.guardians set language='zh-CN' where id=guardian_id_value;
  rejected := false;
  begin perform moasem.create_guardian_consent_request(staff_id_value,pupil_id,document_id_value,repeat('d',64));
  exception when others then if sqlerrm<>'TRANSLATION_REQUIRED' then raise; end if; rejected := true; end;
  if not rejected then raise exception 'Korean silently substituted for missing native copy'; end if;
  update moasem.staff_accounts set active=false where id=staff_id_value;
  rejected := false;
  begin perform moasem.create_guardian_consent_request(staff_id_value,pupil_id,document_id_value,repeat('e',64));
  exception when others then if sqlerrm<>'STAFF_ACCESS_DENIED' then raise; end if; rejected := true; end;
  if not rejected then raise exception 'Inactive staff issued consent'; end if;
  reset role;
  foreach table_name_value in array array['consent_documents','guardian_consent_requests','guardian_consent_records'] loop
    if has_table_privilege('anon','moasem.'||table_name_value,'SELECT') or has_table_privilege('authenticated','moasem.'||table_name_value,'SELECT') then raise exception 'Consent data exposed: %',table_name_value; end if;
    if not (select relrowsecurity from pg_class where oid=('moasem.'||table_name_value)::regclass) then raise exception 'RLS missing: %',table_name_value; end if;
  end loop;
  if has_function_privilege('anon','moasem.access_guardian_consent(text,jsonb)','EXECUTE') or has_function_privilege('authenticated','moasem.access_guardian_consent(text,jsonb)','EXECUTE') then raise exception 'Public DB RPC bypasses app'; end if;
end;
$$;
rollback;
