begin;
do $$
declare inst uuid; teacher uuid; program uuid; pupil uuid; staff uuid; admin_id uuid; outsider uuid; guardian uuid; entry_id uuid:=gen_random_uuid(); payload jsonb; result jsonb; rejected boolean;
begin
 insert into moasem.institutions(name) values('__progress_test__') returning id into inst;
 insert into moasem.instructors(name) values('__progress_test__') returning id into teacher;
 insert into moasem.programs(institution_id,instructor_id,name,starts_on,ends_on,week_count) values(inst,teacher,'Test','2026-01-01','2026-12-31',12) returning id into program;
 staff:=moasem.save_staff_instructor(null,teacher,null,'Test','test-'||gen_random_uuid()||'@example.invalid','',array[program],true);
 insert into moasem.staff_accounts(name,email,role) values('Test','test-'||gen_random_uuid()||'@example.invalid','admin') returning id into admin_id;
 insert into moasem.instructors(name) values('Other') returning id into outsider;
 outsider:=moasem.save_staff_instructor(null,outsider,null,'Other','test-'||gen_random_uuid()||'@example.invalid','',array[]::uuid[],true);
 insert into moasem.guardians(phone,language) values('01000000000','en') returning id into guardian;
 insert into moasem.students(program_id,guardian_id,name,grade) values(program,guardian,'Test pupil',3) returning id into pupil;
 payload:='{"lesson_date":"2026-09-01","book":"수학 3-2","unit":"곱셈","pages":"20~23","next_assignment":"24쪽","learned":"곱셈","difficulties":"받아올림","teacher_note":"내부 메모"}';
 set local role service_role;
 perform moasem.save_student_progress(staff,pupil,entry_id,payload);
 perform moasem.save_student_progress(staff,pupil,entry_id,payload);
 if (select count(*) from moasem.student_progress_entries where student_id=pupil)<>1 then raise exception 'Duplicate retry'; end if;
 rejected:=false;
 begin perform moasem.save_student_progress(staff,pupil,entry_id,payload||'{"pages":"100"}'); exception when others then if sqlerrm<>'PROGRESS_CONFLICT' then raise; end if; rejected:=true; end;
 if not rejected then raise exception 'Changed retry accepted'; end if;
 perform moasem.save_student_progress(admin_id,pupil,gen_random_uuid(),payload||'{"lesson_date":"2026-08-01","pages":"1"}');
 result:=moasem.read_student_progress(staff,pupil);
 if result->'current'->>'pages'<>'20~23' or jsonb_array_length(result->'entries')<>2 then raise exception 'History/current order'; end if;
 rejected:=false;
 begin perform moasem.read_student_progress(outsider,pupil); exception when others then if sqlerrm<>'PROGRAM_ACCESS_DENIED' then raise; end if; rejected:=true; end;
 if not rejected then raise exception 'Foreign instructor read'; end if;
 rejected:=false;
 begin perform moasem.save_student_progress(outsider,pupil,gen_random_uuid(),payload); exception when others then if sqlerrm<>'PROGRAM_ACCESS_DENIED' then raise; end if; rejected:=true; end;
 if not rejected then raise exception 'Foreign instructor write'; end if;
 perform moasem.create_staff_learning_report(staff,pupil,'{"lesson_date":"2026-09-02","solved_count":10,"wrong_count":2,"language":"en"}',array[]::uuid[]);
 result:=moasem.read_student_progress(admin_id,pupil);
 if result->'entries'->0->>'kind'<>'result' or jsonb_array_length(result->'entries'->0->'reports')<>1 then raise exception 'Report history missing'; end if;
 if result->'entries'->0->'reports'->0->>'token' is null then raise exception 'Current report not linked'; end if;
 update moasem.guardian_reports set expires_at=now()-interval '1 day' where student_id=pupil;
 result:=moasem.read_student_progress(staff,pupil);
 if result->'entries'->0->'reports'->0->>'token' is not null then raise exception 'Expired token exposed'; end if;
 for i in 1..22 loop perform moasem.save_student_progress(staff,pupil,gen_random_uuid(),payload); end loop;
 if jsonb_array_length(moasem.read_student_progress(staff,pupil,0)->'entries')<>21 or jsonb_array_length(moasem.read_student_progress(staff,pupil,20)->'entries')<>5 then raise exception 'Pagination broken'; end if;
 update moasem.students set active=false where id=pupil;
 rejected:=false;
 begin perform moasem.save_student_progress(staff,pupil,gen_random_uuid(),payload); exception when others then if sqlerrm<>'STUDENT_INACTIVE' then raise; end if; rejected:=true; end;
 if not rejected then raise exception 'Inactive write'; end if;
 perform moasem.read_student_progress(staff,pupil);
 reset role;
 if has_table_privilege('anon','moasem.student_progress_entries','SELECT') or has_function_privilege('authenticated','moasem.read_student_progress(uuid,uuid,integer)','EXECUTE') or has_table_privilege('service_role','moasem.student_progress_entries','UPDATE') then raise exception 'Privilege leak'; end if;
end $$;
rollback;
select 'progress DB tests passed (rolled back)' as result;
