import {reportResources} from './report-resources'
export function addDays(day:string,n:number){return new Date(Date.parse(day+'T00:00:00Z')+n*86400000).toISOString().slice(0,10)}
export function weekBounds(day:string){const weekday=new Date(day+'T00:00:00Z').getUTCDay();const start=addDays(day,-((weekday+6)%7));return{start,end:addDays(start,6)}}
export function percentage(n:number,d:number){return d?`${Math.round(100*n/d)}%`:'기록 없음'}
export function attendanceRate(rows:any[],type:string){const r=rows.filter(x=>x.session_type===type);return percentage(r.filter(x=>['present','late'].includes(x.status)).length,r.length)}
export function wrongSummary(logs:any[]){const count=new Map<string,number>();for(const l of logs){const names=reportResources(l.resource_snapshot).wrong_types.map(t=>t.name);for(const n of Array.from(new Set(names)))count.set(n,(count.get(n)??0)+1)}return Array.from(count).sort((a,b)=>b[1]-a[1]).map(([name,count])=>({name,count}))}
export function performance(program:any,students:any[],attendance:any[],homework:any[],logs:any[],scores:any[],paper:any,checks:any[],today:string){
 const studentIds=new Set(students.map(s=>s.id));attendance=attendance.filter(x=>studentIds.has(x.student_id));homework=homework.filter(x=>studentIds.has(x.student_id));logs=logs.filter(x=>studentIds.has(x.student_id));scores=scores.filter(x=>studentIds.has(x.student_id));checks=checks.filter(x=>studentIds.has(x.student_id));
 const inPeriod=(date:string)=>date>=program.starts_on&&date<=program.ends_on&&date<=today
 const a=attendance.filter(x=>inPeriod(x.session_date)),h=homework.filter(x=>inPeriod(x.due_on)),l=logs.filter(x=>inPeriod(x.lesson_date)),sc=scores.filter(x=>inPeriod(x.taken_on))
 const pairs=students.flatMap(s=>{const pre=sc.find(x=>x.student_id===s.id&&x.kind==='pre'),post=sc.find(x=>x.student_id===s.id&&x.kind==='post');return pre&&post&&paper?[{pre:100*pre.score/paper.max_score,post:100*post.score/paper.max_score}]:[]})
 const average=(key:'pre'|'post')=>pairs.length?Math.round(pairs.reduce((sum,x)=>sum+x[key],0)/pairs.length*10)/10:null
 const firstEnd=addDays(program.starts_on,27),lastStart=addDays(program.ends_on,-27)
 const wrong=wrongSummary(l),initial=wrongSummary(l.filter(x=>x.lesson_date<=firstEnd)),last=wrongSummary(l.filter(x=>x.lesson_date>=lastStart))
 const targets=new Set<string>();for(const log of l)for(const v of reportResources(log.resource_snapshot,log.video_url).videos)targets.add(log.student_id+'|'+v.url)
 const opened=new Set(checks.filter(c=>targets.has(c.student_id+'|'+c.video_url)&&inPeriod(c.opened_at.slice(0,10))).map(c=>c.student_id+'|'+c.video_url));const confirmed=new Set(checks.filter(c=>c.confirmed_at&&targets.has(c.student_id+'|'+c.video_url)&&inPeriod(c.confirmed_at.slice(0,10))).map(c=>c.student_id+'|'+c.video_url))
 return {program,generated_on:today,paper,student_count:students.length,in_person:attendanceRate(a,'in_person'),zoom:attendanceRate(a,'zoom'),submission:percentage(h.filter(x=>x.status!=='assigned').length,h.length),homework_count:h.length,paired_count:pairs.length,pre:average('pre'),post:average('post'),wrong,initial,last,initial_count:l.filter(x=>x.lesson_date<=firstEnd).length,last_count:l.filter(x=>x.lesson_date>=lastStart).length,windows_overlap:firstEnd>=lastStart,video_open:percentage(opened.size,targets.size),video_confirmed:percentage(confirmed.size,targets.size),students:students.map(s=>{const ownH=h.filter(x=>x.student_id===s.id),ownL=l.filter(x=>x.student_id===s.id),types=wrongSummary(ownL),pre=sc.find(x=>x.student_id===s.id&&x.kind==='pre'),post=sc.find(x=>x.student_id===s.id&&x.kind==='post');return{id:s.id,name:s.name,grade:s.grade,in_person:attendanceRate(a.filter(x=>x.student_id===s.id),'in_person'),zoom:attendanceRate(a.filter(x=>x.student_id===s.id),'zoom'),submission:percentage(ownH.filter(x=>x.status!=='assigned').length,ownH.length),pre:pre&&paper?Math.round(100*pre.score/paper.max_score):null,post:post&&paper?Math.round(100*post.score/paper.max_score):null,comment:types.length?`${types[0].name} 유형이 ${types[0].count}회 기록되어 복습이 필요합니다.`:ownL.length?'학습 결과가 기록되었습니다. 다음 과제 이행을 확인해 주세요.':'학습 결과가 아직 기록되지 않았습니다.'}})}
}
