// Small standards-based OOXML document, stored ZIP entries; no external service.
const xml=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!)).replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,'')
function crc(bytes:Uint8Array){let c=0xffffffff;for(let i=0;i<bytes.length;i++){c^=bytes[i];for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
export function reportDocx(lines:string[]){
 const files:Record<string,string>={'[Content_Types].xml':'<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>','_rels/.rels':'<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>','word/document.xml':'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>'+lines.map((line,i)=>`<w:p><w:pPr><w:spacing w:after="120"/></w:pPr><w:r><w:rPr><w:rFonts w:ascii="Arial" w:eastAsia="S-Core Dream"/><w:sz w:val="${i===0?32:22}"/>${i===0?'<w:b/>':''}</w:rPr><w:t xml:space="preserve">${xml(line)}</w:t></w:r></w:p>`).join('')+'<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1134" w:right="1134" w:bottom="1134" w:left="1134"/></w:sectPr></w:body></w:document>'}
 const chunks:Uint8Array[]=[],central:Uint8Array[]=[];let offset=0
 for(const [name,content]of Object.entries(files)){const n=new TextEncoder().encode(name),b=new TextEncoder().encode(content),header=new Uint8Array(30+n.length),h=new DataView(header.buffer);h.setUint32(0,0x04034b50,true);h.setUint16(4,20,true);h.setUint32(14,crc(b),true);h.setUint32(18,b.length,true);h.setUint32(22,b.length,true);h.setUint16(26,n.length,true);header.set(n,30);chunks.push(header,b);const entry=new Uint8Array(46+n.length),e=new DataView(entry.buffer);e.setUint32(0,0x02014b50,true);e.setUint16(4,20,true);e.setUint16(6,20,true);e.setUint32(16,crc(b),true);e.setUint32(20,b.length,true);e.setUint32(24,b.length,true);e.setUint16(28,n.length,true);e.setUint32(42,offset,true);entry.set(n,46);central.push(entry);offset+=header.length+b.length}
 const size=central.reduce((sum,b)=>sum+b.length,0),end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,central.length,true);v.setUint16(10,central.length,true);v.setUint32(12,size,true);v.setUint32(16,offset,true);const output=new Uint8Array(offset+size+22);let pos=0;for(const b of [...chunks,...central,end]){output.set(b,pos);pos+=b.length}return output
}
export const reportMethod='출석률: 기록된 수업 중 출석·지각 비율. 과제 제출률: 프로그램 기간 내 오늘까지 마감된 과제 중 제출·강사 확인 비율. 사전·사후 평균: 동일 진단지로 두 점수가 모두 등록된 학생만 100점 기준 비교. 오답: 문제 수가 아닌 해당 유형이 기록된 수업 횟수. 영상: 연결 영상·학생 조합 기준이며 완료는 학생의 자기 확인입니다. 현재 프로그램 소속 학생(중지 포함)을 대상으로 합니다.'
export function reportLines(r:any,anonymous:boolean){const name=(s:any,i:number)=>anonymous?`학생 ${String(i+1).padStart(2,'0')}`:s.name;return ['모아셈 프로그램 성과보고서',`기관: ${r.program.institution?.name??''}`,`프로그램: ${r.program.name}`,`기간: ${r.program.starts_on} ~ ${r.program.ends_on} / ${r.program.week_count}주`,`작성 기준일: ${r.generated_on} / 학생 ${r.student_count}명`,`대면 출석률 ${r.in_person} / 줌 출석률 ${r.zoom}`,`과제 제출률 ${r.submission} (대상 ${r.homework_count}건)`,`사전 평균 ${r.pre??'미등록'} → 사후 평균 ${r.post??'미등록'} (100점 기준, 대응 학생 ${r.paired_count}명)`,`진단지: ${r.paper?.title??'미등록'}`,`영상 열람률 ${r.video_open} / 시청 완료 자기 확인률 ${r.video_confirmed}`,'오답 유형 변화: 시작 4주 → 마지막 4주',...(r.windows_overlap?['※ 프로그램 기간이 짧아 두 비교 구간이 겹칩니다.']:[]),...Array.from(new Set<string>([...r.initial,...r.last].map((x:any)=>x.name))).map(n=>`${n}: ${r.initial_count?(r.initial.find((x:any)=>x.name===n)?.count??0)+'회':'기록 없음'} → ${r.last_count?(r.last.find((x:any)=>x.name===n)?.count??0)+'회':'기록 없음'}`),'학생별 결과',...r.students.flatMap((s:any,i:number)=>[`${name(s,i)} / ${s.grade}학년 / 대면 ${s.in_person} / 줌 ${s.zoom} / 과제 ${s.submission} / 사전 ${s.pre??'—'} → 사후 ${s.post??'—'}`,s.comment]),'집계 기준',reportMethod,'코멘트는 저장된 기록으로 만든 정형 문장입니다. AI 평가가 아닙니다.']}
