'use client'
import {useEffect,useRef,useState} from 'react'
import {Icon} from '@/app/components/workspace'
export default function StudentPage({params}:{params:{token:string}}){
 const [data,setData]=useState<any>(null),[view,setView]=useState('home'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[chosen,setChosen]=useState(''),[file,setFile]=useState<Blob|null>(null);const id=useRef('')
 const api=`/api/student/${params.token}`
 useEffect(()=>{let alive=true;fetch(api,{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(alive)setData(d)}).catch(e=>{if(alive)setMessage(e.message)});return()=>{alive=false}},[api])
 async function reload(){const r=await fetch(api,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setData(d)}
 async function choosePhoto(f:File|undefined){setFile(null);id.current='';if(!f)return;setBusy(true);try{const bitmap=await createImageBitmap(f),ratio=Math.min(1,1800/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*ratio);canvas.height=Math.round(bitmap.height*ratio);canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/jpeg',0.82));if(!blob||blob.size>3145728)throw Error('사진이 너무 커요. 조금 작게 찍어 주세요.');setFile(blob);id.current=crypto.randomUUID();setMessage('사진을 골랐어요. 올리기를 눌러 주세요.')}catch{setMessage('이 사진을 읽지 못했어요. JPG 또는 PNG 사진을 골라 주세요.')}finally{setBusy(false)}}
 async function upload(){if(!file||!chosen||busy)return;setBusy(true);try{const body=new FormData();body.set('photo',file,'homework.jpg');body.set('id',id.current);body.set('homework_id',chosen);const r=await fetch(`${api}/photo`,{method:'POST',body}),d=await r.json();if(!r.ok)throw Error(d.error);setFile(null);id.current='';setMessage('사진을 올렸어요!');await reload()}catch(e){setMessage(e instanceof Error?e.message:'다시 눌러 주세요.')}finally{setBusy(false)}}
 async function video(url:string,confirmed:boolean){try{const r=await fetch(api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url,confirmed})});if(!r.ok)throw Error('영상 기록을 저장하지 못했어요. 다시 눌러 주세요.');if(confirmed){await reload();setMessage('봤다고 표시했어요.')}}catch(e){setMessage(String(e))}}
 return <main className="student-shell"><header><span className="eyebrow">MOAKIT · 모아셈</span><h1>{data?`${data.student.name}의 공부방`:'공부방'}</h1>{view!=='home'&&<button className="button" disabled={busy} onClick={()=>{setView('home');setMessage('')}}>처음으로</button>}</header><p role="status">{message}</p>{!data?<p>선생님이 보내 준 링크로 들어와 주세요.</p>:view==='home'?<div className="student-actions"><button onClick={()=>setView('class')}><Icon name="video" size={48}/>수업 입장</button><button onClick={()=>setView('homework')}><Icon name="report" size={48}/>숙제 올리기</button><button onClick={()=>setView('videos')}><Icon name="video" size={48}/>내 영상</button></div>:view==='class'?<section className="surface"><h2>줌 수업</h2>{data.program.zoom_join_url?<a className="button button-primary" href={data.program.zoom_join_url} target="_blank" rel="noopener noreferrer">줌 앱으로 열기</a>:<p>선생님이 수업을 준비하고 있어요.</p>}</section>:view==='homework'?<section className="surface"><h2>숙제 올리기</h2>{!data.homework.length?<p>아직 숙제가 없어요.</p>:<><label className="field"><span>숙제 고르기</span><select value={chosen} disabled={busy} onChange={e=>{setChosen(e.target.value);setFile(null);id.current=''}}><option value="">골라 주세요</option>{data.homework.map((h:any)=><option key={h.id} value={h.id}>{h.title} · {h.status==='checked'?'확인 완료':h.status==='submitted'?'제출했어요':h.due_on+'까지'}</option>)}</select></label>{chosen&&(()=>{const h=data.homework.find((x:any)=>x.id===chosen);return <><p>{h.details}</p><p>올린 사진 {h.photos.length}장 / 5장</p>{h.status!=='checked'&&h.photos.length<5&&<><label className="field"><span>사진 찍거나 고르기</span><input key={chosen+String(!file)} type="file" accept="image/*" disabled={busy} onChange={e=>choosePhoto(e.target.files?.[0])}/></label><button className="button button-primary" disabled={busy||!file} onClick={upload}>{busy?'올리는 중…':'사진 올리기'}</button></>}</>})()}</>}</section>:<section className="surface"><h2>내 영상</h2>{!data.videos.length?<p>선생님이 영상을 준비하고 있어요.</p>:data.videos.map((v:any)=><article className="student-video" key={v.url}><h3>{v.title||'보충 영상'}</h3><a className="button button-primary" href={v.url} target="_blank" rel="noopener noreferrer" onClick={()=>void video(v.url,false)}>영상 보기</a><button className="button" onClick={()=>video(v.url,true)} disabled={!!data.checks.find((c:any)=>c.video_url===v.url&&c.confirmed_at)}>{data.checks.find((c:any)=>c.video_url===v.url&&c.confirmed_at)?'봤어요 ✓':'다 봤어요'}</button></article>)}</section>}</main>
}
